name: Gitleak

on: 
  pull_request:
    branches: [master]

jobs:
  gitleaks-history:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
  
      - name: Run Gitleaks on full history
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}