name: SonarCloud 

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  sonarcloud: 
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Download test results (win48)
        uses: dawidd6/action-download-artifact@v3
        with:
          name: test-results-win48
          path: TestResults          
          workflow: gate.yml
          commit: ${{ github.event.workflow_run.head_sha }}

      - name: Download test results (win9)
        uses: dawidd6/action-download-artifact@v3
        with:
          name: test-results-win9
          path: TestResults          
          workflow: gate.yml
          commit: ${{ github.event.workflow_run.head_sha }}

      - name: Download test results (coverage9)
        uses: dawidd6/action-download-artifact@v3
        with:
          name: test-results-coverage9
          path: TestResults 
          workflow: gate.yml
          commit: ${{ github.event.workflow_run.head_sha }}

      - name: Install lcov-to-cobertura-xml
        run: pip install lcov_cobertura

      - name: Convert lcov to cobertura
        run: lcov_cobertura TestResults/coverage.net9.0.info -o TestResults/coverage.net9.0.info.xml 

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src  
          args: >
            -Dsonar.organization=jfwang 
            -Dsonar.projectKey=jfwangncs_jfYu
            -Dsonar.cs.vstest.reportsPaths=TestResults/*.trx
            -Dsonar.cs.opencover.reportPaths=TestResults/coverage.net9.0.info.xml

